### ISSUE TITLE
Flag issue on Hashlink Target

### ISSUE THREAD

**Issue by Eiyeron** [Yanrishatum/haxe-format-tiled#6]
Hello. I'm currently prototyping stuff to see how Heaps work and I wanted to use this library to parse .tmx files. It's going more or less well. I'm hitting some design limits but I'm currently circumventing them.

I got an issue that rose: the tweak you're doing in Reader.hx:314 (`if (flipH) tile = -tile;`) doesn't seem to work when targeting Hashlink. I have to comment out or remove the line to have an expected behavior (correct GID with correct flags).

I guess this line exists due to the limitation of the Int type (32-bit-ish on all platforms), but I'm wondering what would be the best way to manage that.

Best regards.

**Comment by Yanrishatum** [comment]
Yes, it's primarily due to Int32 limitations, and was made by keeping in mind that last bit represent value sign. I assume HashLink uses 64-bit integers for Int? 
(To be honest I don't even know if those flags are used at all and just some legacy mumbo-jumbo, because they are in the format docs, but never seen it used anywhere)
I'll think on proper solution, but for now will settle with simple hotfix (I'd be glad if you check it out or provide minimal heaps test-case).

By the way, if you want to bring up topic about design limitations, I'm open for feedback. I want to make lower-level version of parser that would work on callbacks for just-in-time map processing instead of getting parsed structure and only then do in-game processing, but that's just plans as of now.

**Comment by Eiyeron** [comment]
Yeah, the flags are indeed used, the orthogonal-outside example holds flipped tiles, it's been a good way to notice this issue. The flip bits are referenced [here](http://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping).

I read up a bit about HL, and it doesn't seem to have U32 or I/U64.  Int64 also seems to be unavailable. So I'm going to bet on the inexistance of 64-bit integers on this target.

I'll eventually try to make a minimal repro case, thanks for the idea. Not a lot to shelve off what I currently have.

Edit, here you go. Just run build_hl.hxml and run `hl out.hl`. I'm using Haxe 4.0-rc 4, Hashlink 1.6.0 and Heaps 1.2.0
[Issue reproduction.zip](https://github.com/Yanrishatum/haxe-format-tiled/files/2189238/Issue.reproduction.zip)

Here's the expected result (it should like this with my tweak)
![image](https://user-images.githubusercontent.com/936086/42643533-aa03f76e-85f9-11e8-9d97-3762cf80418e.png)

**Comment by Yanrishatum** [comment]
Thanks. After checking out, it turned out to be global bug. After testing that line led to id corruption on all platforms. Probably something changed in Std.parseInt implementation?

**Comment by Eiyeron** [comment]
I haven't really followed the changes with Std.parseint, but IIRC there was an issue with PHP at one moment due to the version bump to 7.

Anyway, thanks for the fix!
